scrape.py
=> Move check of top 15 links to link aggregator loop

scheduler.py
removed print(Anything), in scheduler.py
=> removed print(Anything)

scrape.py
=> scrape: "html" parser explicitly mentioned

UIP.py
Now users can start UIP in online mode by just typing 'python3 UIP.py' in command line or in offline mode by typing 'pyhton3 UIP.py --offline' in command line.
Fixes #64
=> UIP.py: Added Option to start in offline mode through command line.

uiplib/scheduler.py, uiplib/setWallpaper.py
just removed the print keywords in the setWallpaper.py and schedular,py to avoid random no.
=> issue no.  #77

uiplib/scheduler.py
=> UIPlib/schedular.py: removed function schedule time

uiplib/scheduler.py
Now users can skip the current wallpaper by just pressing enter.
Fixes #89
=> uiplib/scheduler.py: Feature added to skip wallpapers

UIP.py
=> Add flag options for flush and offline modes

README.md
Renamed the screenshots area and moved it above the set up
Fixes #72
=> README.md : Fixes #72 Renamed the screenshots area

uiplib/UIP.py
it will left an exit message on user intrupt
=> UIP.py: added exit message

uiplib/scrape.py
=> uiplib/scrape.py: Now all the images are successfully downloaded --teja:315

setup.py, uiplib/UIP.py, uiplib/scheduler.py, uiplib/scrape.py, uiplib/settings.py
=> Add flag option for count setting

uiplib/UIP.py
=> UIP.py: Modified the welcome message.

uiplib/scheduler.py
=> Limited CPU% usage under 2%

setup.py, uiplib/UIP.py, uiplib/scheduler.py, uiplib/scrape.py, uiplib/settings.py
Make changes in scrape.py, constants.py & scheduler.py to allow fetching 
wallpapers from unsplash.com
Closes #111
=> uiplib: Use unsplash.com for fetching wallpapers

README.md
Seperate installation for users and developers
=> Clean setup in README

tests/test_scrape.py
Add a function to test_unsplash_image_links
Fixes #165
=> tests: Add test for Unsplash.com

setup.py
Adds 4 new sites to be installed by default.
Fixes #159
=> setup.py: Add more sites by default

setup.py, uiplib/UIP.py
Changed default folder from ~/.uip to /uip-pics.
This prevents root privlage problems in linux.
Fixes #142
=> Fix permission issues

setup.py, uiplib/utils.py
=> Check for python3.5 interpreter

.coafile, setup.py, test-requirements.txt, tests/test_scrape.py, tests/test_utils.py, uiplib/GUI.py, uiplib/UIP.py, uiplib/scheduler.py, uiplib/scrape.py, uiplib/setWallpaper.py, uiplib/settings.py, uiplib/utils.py
Add linting with PEP8Bear using coala-bears
=> Lint with PEP8Bear

README.md
=> Readme: Add instructions for GUI in Run

.travis.yml, uiplib/UIP.py, uiplib/utils.py
Adds an exit function to utils.py
that exits UIP gracefully and
properly.
Fixes #181
=> utils.py: Add exit wrapper

CHANGELOG.md
=> CHANGELOG.md: Changes upto v0.0.2

setup.py, uiplib/GUI.py, uiplib/scrape.py
Images are sourced using api.desktoppr.com
Resolves issue #212
=> Add image source: desktoppr.com

uiplib/GUI.py
Hides the subreddit textbox and label when
Reddit checkbutton is unclicked.
Fixes #211
=> GUI.py: Destroy subreddit widgets

uiplib/UIP.py, uiplib/settings.py
Stop creation of useless pid-file,
which causes error in uip_exit()
Fixes #225
=> Do not allow --ui and --service together

README.md
=> Changed UIP.py to UIP in README.md

setup.py, tests/test_utils.py, uiplib/GUI.py, uiplib/UIP.py, uiplib/scheduler.py, uiplib/utils/setupUtils.py, uiplib/utils/utils.py
Made a new folder utils in uiplib, and added the setup required methods
in setupUtils.py and others are kept unchanged in utils.py only.
Fixes #224
=> Differentiated setup and regular utils.

README.md
to do that run : "pip install setuptools"
Fixes #183
=> README.md: add setuptools required in readme

README.md
=> README.md: add git clone step

uiplib/GUI.py, uiplib/utils/utils.py
Fixes https://github.com/NIT-dgp/UIP/issues/209
=> GUI: Add default options to settings

.coafile, UIP, setup.py, uiplib/GUI.py, uiplib/UIP.py, uiplib/scheduler.py, uiplib/scrape/onlineFetch.py, uiplib/scrape/scrape.py, uiplib/setWallpaper.py, uiplib/settings.py, uiplib/utils/setupUtils.py, uiplib/utils/utils.py
Also enable PyDocStyleBear for `coala` to restrict undocument code pushes.
=> Add docstrings for all modules

uiplib/scrape/scrape.py
Added a method for retrieving proxy from system variables in scrape.py
Fixes #178
=> Added proxy support

uiplib/GUI.py
This lets the user preview the whole wallpaper
Fixes #227
=> GUI.py: Resize image adequately

setup.py
I added a newline after each JSON object.
Fixes https://github.com/NIT-dgp/UIP/issues/158
=> setup.py: Makes setting.json pretty

Makefile
make lint: checks for lint errors
make test: checks with pytest
sudo make install: installs the UIP module
sudo make clean: cleans the directories
sudo make uninstall: removes the UIP module
=> Makefile: Add a makefile for UNIX based systems

uiplib/gui/mainGui.py
=> mainGui.py: Makes previous button work correctly

setup.py, uiplib/gui/settingsTab.py, uiplib/settings.py
=> GUI:add default button

uiplib/gui/settingsTab.py
=> GUI: Update View Once Reset is pressed

uiplib/gui/generalTab.py
Remove the downloadBtn from uiplib/gui/generalTab.py
Fixes #284
=> GUI: Remove unnecessary downloadBtn variable

uiplib/gui/gallery.py, uiplib/gui/mainGui.py, uiplib/uipImage.py
Fixes https://github.com/NIT-dgp/UIP/issues/147
=> Gallery: Add Blur Feature

uiplib/gui/generalTab.py
=> GUI: Arranged Set Wallpaper and Flush button side by side

uiplib/gui/gallery.py, uiplib/gui/generalTab.py
=> GUI: Adds delay to blur to reduce render cycles

Makefile, test-requirements.txt
requirements.txt: Use cib to install bears
Makefile: Change test-install script
Fixes #308
=> CI: Install only required bears

setup.py, uiplib/gui/generalTab.py, uiplib/gui/mainGui.py, uiplib/settings.py
creates a favourite_pics folder inside .uip directory which save user's fav wallpaper and also immunes them against flush action.
Fixes #121
=> GUI:add favourite option

uiplib/gui/mainGui.py
Blur bar resets to initial level, everytime picture is changed.
Fixes #296
=> GUI:reset blur bar

uiplib/gui/mainGui.py, uiplib/gui/settingsTab.py, uiplib/settings.py
=> GUI:added settings for favorite option

uiplib/gui/gallery.py, uiplib/gui/generalTab.py, uiplib/gui/mainGui.py, uiplib/scheduler.py
Fix mistakes made in previous commits.
Renamed functions are now called correctly.
After a `Flush` the started download will update
the UI.
=> Fix broken Gui

uiplib/UIP.py, uiplib/gui/mainGui.py, uiplib/scheduler.py
Make scheduler class non-threaded while making the scheduler
functions threaded
Fixes https://github.com/NIT-dgp/UIP/issues/334
=> Scheduler: Seperate thread for schedule

uiplib/scheduler.py
=> uiplib/scheduler.py: resolves issue #338

uiplib/gui/mainGui.py
=> GUI:Displays the Error dialog box.

uiplib/gui/mainGui.py
fixes #346 
Also added a message box to intimate the user if the pic is added to favourites!
=> Remove errors while saving to favourites

README.md
Corrected the spellings of Separation and Privilege.
A first-timer here.
=> ReadMe Correction, Issue #156

uiplib/UIP.py, uiplib/scheduler.py
Fixes https://github.com/NIT-dgp/UIP/issues/351
CC @SACHIN-13  @nkprince007
=> scheduler: Correct schedule Thread use

README.md
Shortlog : NOte changed to Note
Fixes #265
=> NOte changed to Note

uiplib/UIP.py, uiplib/gui/mainGui.py, uiplib/scheduler.py
Name of the class scheduler changed to Scheduler: scheduler.py,mainGui.py,UIP.py
class 'scheduler' changed to 'Scheduler' in all classes of UIP
Fixes #268
=> Name of the class scheduler changed to Scheduler

.travis.yml, Makefile, test-requirements.txt
- Use GitMate CI instead of ``coala --ci``
=> travis: Remove coala checks

tests/test_scrape.py, tests/test_wallpaper.py, uiplib/UIP.py, uiplib/Wallpaper.py, uiplib/scheduler.py, uiplib/scrape.py, uiplib/utils/utils.py
Also clean up a lot of related code
=> Scheduler: Make 1 download per wallpaper
